[package]
name = "coyote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
rust_decimal = "1.17"
rust_decimal_macros = "1.17"
blake2 = "0.9"
crypto = {path = "crypto"}


